DO $$ 
DECLARE 
    EMP_ID INT := 001;
    EMP_NAME VARCHAR(40) := 'HARRY';
    EMP_SALARY NUMERIC := 50000;
BEGIN 
    RAISE NOTICE 'EMPLOYEE ID: %', EMP_ID;
    RAISE NOTICE 'EMPLOYEE NAME: %', EMP_NAME;
    RAISE NOTICE 'EMPLOYEE SALARY: %', EMP_SALARY;
    RAISE NOTICE 'HOUSE RENT ALLOWANCE: %', (0.25 * EMP_SALARY);

    IF EMP_SALARY > 49000 THEN 
        RAISE NOTICE 'YOU NEED TO PAY TAX';
    ELSE 
        RAISE NOTICE 'YOU WILL NOT PAY TAX';
    END IF;
END $$;
