BEGIN;
COMMIT;
DROP TABLE IF EXISTS BOOK_ISSUED CASCADE;
CREATE TABLE BOOK_ISSUED(
	ISSUE_ID INT PRIMARY KEY,
	USER_ID INT NOT NULL,
	BOOK_ID INT NOT NULL,
	FOREIGN KEY(USER_ID) REFERENCES LIBRARY(USER_ID),
	FOREIGN KEY(BOOK_ID) REFERENCES BOOK(BOOK_ID)
);
DROP TABLE IF EXISTS BOOK; 
CREATE TABLE BOOK (
	BOOK_ID INT PRIMARY KEY,
	BOOK_NAME VARCHAR(20) NOT NULL,
	BOOK_AUTH VARCHAR(20) NOT NULL
);

---- <CHECK> IS USED TO SET A CONSTRAINT IN A TABEL
ALTER TABLE BOOK
ADD BOOK_COUNT INT CHECK( BOOK_COUNT > 0) NOT NULL;

INSERT INTO BOOK VALUES
	(01, 'HARRY PORTER', 'DAVID', 3),
	(02, '1984', 'WILIIAMS', 2);

DROP TABLE IF EXISTS LIBRARY;
CREATE TABLE LIBRARY (
	USER_ID INT PRIMARY KEY,
	NAME VARCHAR(20) NOT NULL,
	AGE INT CHECK( AGE > 17) NOT NULL
);

INSERT INTO LIBRARY VALUES
	(01, 'RISHAV GIRI', 19),
	(02, 'GEORGE OLIVER', 25);




ALTER TABLE BOOK_ISSUED
ADD ISSUE_DATE DATE;

INSERT INTO BOOK_ISSUED VALUES
	(01, 02, 01, '2006-01-08');

UPDATE BOOK_ISSUED
SET ISSUE_DATE='2025-04-12'
WHERE USER_ID = 01;

SELECT * FROM BOOK_ISSUED;
SELECT * FROM LIBRARY;
SELECT * FROM BOOK;


ROLLBACK;
